### 

GET http://localhost:8080/hello/amtux

###


GET http://localhost:8080/hello/test

###



GET http://localhost:8080/hello/one

###



GET http://localhost:8080/hello/two

###


GET http://localhost:8080/hello/three

###
